spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/techday?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: pass
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080
microservices:
  mskotlin:
     url: http://localhost:8081/mskotlin
  msjavaconsumer:
     queue-name: car-queue
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mariadb:3306/techday?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
#---
#spring:
#  profiles: kubernetes
#  datasource:
#    url: jdbc:mysql://mariadb-service:3306/techday?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  rabbitmq:
#    host: rabbitmq-service
#    port: 5672
#    username: guest
#    password: guest